/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    korisnici: KorisniciAuthOperations;
  };
  blocks: {};
  collections: {
    upiti: Upiti;
    poslovnice: Poslovnice;
    proizvodi: Proizvodi;
    usluge: Usluge;
    akcije: Akcije;
    objave: Objave;
    'cesta-pitanja': CestaPitanja;
    tim: Tim;
    recenzije: Recenzije;
    mediji: Mediji;
    korisnici: Korisnici;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    upiti: UpitiSelect<false> | UpitiSelect<true>;
    poslovnice: PoslovniceSelect<false> | PoslovniceSelect<true>;
    proizvodi: ProizvodiSelect<false> | ProizvodiSelect<true>;
    usluge: UslugeSelect<false> | UslugeSelect<true>;
    akcije: AkcijeSelect<false> | AkcijeSelect<true>;
    objave: ObjaveSelect<false> | ObjaveSelect<true>;
    'cesta-pitanja': CestaPitanjaSelect<false> | CestaPitanjaSelect<true>;
    tim: TimSelect<false> | TimSelect<true>;
    recenzije: RecenzijeSelect<false> | RecenzijeSelect<true>;
    mediji: MedijiSelect<false> | MedijiSelect<true>;
    korisnici: KorisniciSelect<false> | KorisniciSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    pocetna: Pocetna;
    navigacija: Navigacija;
    podesavanja: Podesavanja;
  };
  globalsSelect: {
    pocetna: PocetnaSelect<false> | PocetnaSelect<true>;
    navigacija: NavigacijaSelect<false> | NavigacijaSelect<true>;
    podesavanja: PodesavanjaSelect<false> | PodesavanjaSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Korisnici;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface KorisniciAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Svi upiti sa stranice na jednom mjestu. CSV izvoz: /api/upiti/izvoz (otvoriti u novom tabu dok ste prijavljeni).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upiti".
 */
export interface Upiti {
  id: number;
  vrsta: 'zakazivanje' | 'doktor' | 'poslovnica' | 'podrska' | 'kupovina' | 'povratni-poziv';
  status: 'novo' | 'u-toku' | 'rijeseno';
  poslovnica?: (number | null) | Poslovnice;
  dodijeljeno?: (number | null) | Korisnici;
  ime: string;
  telefon: string;
  email?: string | null;
  poruka?: string | null;
  preferiraniTermin?: string | null;
  proizvod?: (number | null) | Proizvodi;
  izvorStranica?: string | null;
  saglasnost: boolean;
  /**
   * Vidljivo samo u administraciji.
   */
  biljeske?:
    | {
        tekst: string;
        autor?: (number | null) | Korisnici;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Lokacije Audio BM poslovnica — adrese, telefoni, radno vrijeme.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poslovnice".
 */
export interface Poslovnice {
  id: number;
  naziv: string;
  /**
   * Dio web-adrese, npr. „banja-luka". Ostavite prazno za automatsko popunjavanje.
   */
  slug: string;
  grad: string;
  adresa: string;
  /**
   * npr. 44.7722
   */
  geoSirina?: number | null;
  /**
   * npr. 17.1910
   */
  geoDuzina?: number | null;
  telefoni?:
    | {
        oznaka?: string | null;
        broj: string;
        id?: string | null;
      }[]
    | null;
  emaili?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  viber?: string | null;
  whatsapp?: string | null;
  /**
   * Unesite radno vrijeme za svaki dan. Dok nije potvrđeno, na stranici se prikazuje napomena da se radno vrijeme provjeri telefonom.
   */
  radnoVrijeme?:
    | {
        dan: 'ponedjeljak' | 'utorak' | 'srijeda' | 'cetvrtak' | 'petak' | 'subota' | 'nedjelja';
        od?: string | null;
        do?: string | null;
        zatvoreno?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Dok nije označeno, stranica prikazuje [RADNO_VRIJEME_PLACEHOLDER] napomenu.
   */
  radnoVrijemePotvrdjeno?: boolean | null;
  fotografije?: (number | Mediji)[] | null;
  opis?: string | null;
  googleMapsLink?: string | null;
  novaPoslovnica?: boolean | null;
  aktivna?: boolean | null;
  redoslijed?: number | null;
  /**
   * Kako se stranica prikazuje na Google-u. Ostavite prazno za automatski tekst.
   */
  seo?: {
    naslov?: string | null;
    opis?: string | null;
    slika?: (number | null) | Mediji;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Slike i dokumenti. Pri otpremanju se automatski prave optimizovane verzije.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediji".
 */
export interface Mediji {
  id: number;
  /**
   * Kratak opis za čitače ekrana i pretraživače, npr. „Zaušni slušni aparat Bernafon".
   */
  alt: string;
  lqip?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    mala?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    srednja?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    velika?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xl?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    puna?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Korisnici administracije i njihove uloge.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "korisnici".
 */
export interface Korisnici {
  id: number;
  ime: string;
  uloga: 'vlasnik' | 'urednik' | 'poslovnica';
  /**
   * Obavezno za ulogu „Poslovnica".
   */
  poslovnica?: (number | null) | Poslovnice;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'korisnici';
}
/**
 * Slušni aparati (savjetovanje, bez cijene) i maloprodajni artikli (baterije, čepovi, pribor…).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proizvodi".
 */
export interface Proizvodi {
  id: number;
  naziv: string;
  /**
   * Dio web-adrese, npr. „banja-luka". Ostavite prazno za automatsko popunjavanje.
   */
  slug: string;
  nacin: 'konsultacija' | 'maloprodaja';
  kategorija:
    | 'slusni-aparati'
    | 'baterije'
    | 'cepovi-za-usi'
    | 'pribor-i-odrzavanje'
    | 'kucni-medicinski-aparati'
    | 'slusni-implanti'
    | 'profesionalna-oprema';
  brend?:
    | (
        | 'Bernafon'
        | 'Unitron'
        | 'Varta'
        | 'Cochlear'
        | 'GSI'
        | 'Otometrics'
        | 'Dynamic Ear Company'
        | 'Dreve'
        | 'Alerta'
        | 'Ostalo'
      )
    | null;
  tipAparata?: ('kanalni' | 'zausni' | 'zausni-snazni') | null;
  /**
   * Ostavite prazno ako cijena nije potvrđena — prikazaće se „Cijena na upit".
   */
  cijena?: number | null;
  staraCijena?: number | null;
  cijenaOd?: number | null;
  cijenaDo?: number | null;
  /**
   * npr. „Cijena zavisi od modela i stepena oštećenja sluha."
   */
  cijenaNapomena?: string | null;
  kratkiOpis?: string | null;
  opis?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slike: (number | Mediji)[];
  istaknut?: boolean | null;
  aktivan?: boolean | null;
  /**
   * Za 301 preusmjeravanja sa stare stranice.
   */
  legacyHandle?: string | null;
  /**
   * Kako se stranica prikazuje na Google-u. Ostavite prazno za automatski tekst.
   */
  seo?: {
    naslov?: string | null;
    opis?: string | null;
    slika?: (number | null) | Mediji;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Usluge — besplatna provjera sluha, prilagođavanje i servis, kohlearni implanti…
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usluge".
 */
export interface Usluge {
  id: number;
  naziv: string;
  /**
   * Dio web-adrese, npr. „banja-luka". Ostavite prazno za automatsko popunjavanje.
   */
  slug: string;
  kratkiOpis: string;
  ikona?: ('ear' | 'settings' | 'stethoscope' | 'chat' | 'shield') | null;
  koraci?:
    | {
        naslov: string;
        opis: string;
        id?: string | null;
      }[]
    | null;
  trajanje?: string | null;
  zaKoga?: string | null;
  sadrzaj?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slika?: (number | null) | Mediji;
  redoslijed?: number | null;
  aktivna?: boolean | null;
  /**
   * Kako se stranica prikazuje na Google-u. Ostavite prazno za automatski tekst.
   */
  seo?: {
    naslov?: string | null;
    opis?: string | null;
    slika?: (number | null) | Mediji;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Promocije i popusti. Akcija se automatski sklanja sa stranice nakon datuma isteka.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "akcije".
 */
export interface Akcije {
  id: number;
  naslov: string;
  /**
   * Dio web-adrese, npr. „banja-luka". Ostavite prazno za automatsko popunjavanje.
   */
  slug: string;
  kratkiOpis: string;
  sadrzaj?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slika?: (number | null) | Mediji;
  vrijediOd: string;
  vrijediDo: string;
  proizvodi?: (number | Proizvodi)[] | null;
  poslovnice?: (number | Poslovnice)[] | null;
  istaknutaNaPocetnoj?: boolean | null;
  /**
   * Kako se stranica prikazuje na Google-u. Ostavite prazno za automatski tekst.
   */
  seo?: {
    naslov?: string | null;
    opis?: string | null;
    slika?: (number | null) | Mediji;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Savjeti i novosti. Nacrt nije vidljiv na stranici dok se ne objavi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "objave".
 */
export interface Objave {
  id: number;
  naslov: string;
  /**
   * Dio web-adrese, npr. „banja-luka". Ostavite prazno za automatsko popunjavanje.
   */
  slug: string;
  kategorija: 'savjeti' | 'novosti' | 'sarajevo';
  datumObjave?: string | null;
  izvod: string;
  naslovnaSlika?: (number | null) | Mediji;
  sadrzaj: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  autor?: (number | null) | Tim;
  /**
   * Kako se stranica prikazuje na Google-u. Ostavite prazno za automatski tekst.
   */
  seo?: {
    naslov?: string | null;
    opis?: string | null;
    slika?: (number | null) | Mediji;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Zaposleni — prikazuju se na stranici „Naš tim" i na stranicama poslovnica.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tim".
 */
export interface Tim {
  id: number;
  ime: string;
  /**
   * npr. „dipl. defektolog — audiolog"
   */
  titula?: string | null;
  fotografija?: (number | null) | Mediji;
  poslovnica?: (number | null) | Poslovnice;
  jezici?:
    | {
        jezik: string;
        id?: string | null;
      }[]
    | null;
  biografija?: string | null;
  redoslijed?: number | null;
  aktivan?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pitanja i odgovori. Redoslijed mijenjate prevlačenjem u listi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cesta-pitanja".
 */
export interface CestaPitanja {
  id: number;
  _order?: string | null;
  pitanje: string;
  odgovor: string;
  grupa: 'prva-posjeta' | 'cijene-i-refundacija' | 'aparati-i-odrzavanje' | 'servis-i-garancija';
  naPocetnoj?: boolean | null;
  aktivno?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Iskustva korisnika. Na stranici se prikazuju samo odobrene recenzije.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recenzije".
 */
export interface Recenzije {
  id: number;
  ime: string;
  poslovnica?: (number | null) | Poslovnice;
  tekst: string;
  ocjena: number;
  odobreno?: boolean | null;
  istaknuta?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'upiti';
        value: number | Upiti;
      } | null)
    | ({
        relationTo: 'poslovnice';
        value: number | Poslovnice;
      } | null)
    | ({
        relationTo: 'proizvodi';
        value: number | Proizvodi;
      } | null)
    | ({
        relationTo: 'usluge';
        value: number | Usluge;
      } | null)
    | ({
        relationTo: 'akcije';
        value: number | Akcije;
      } | null)
    | ({
        relationTo: 'objave';
        value: number | Objave;
      } | null)
    | ({
        relationTo: 'cesta-pitanja';
        value: number | CestaPitanja;
      } | null)
    | ({
        relationTo: 'tim';
        value: number | Tim;
      } | null)
    | ({
        relationTo: 'recenzije';
        value: number | Recenzije;
      } | null)
    | ({
        relationTo: 'mediji';
        value: number | Mediji;
      } | null)
    | ({
        relationTo: 'korisnici';
        value: number | Korisnici;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'korisnici';
    value: number | Korisnici;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'korisnici';
    value: number | Korisnici;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upiti_select".
 */
export interface UpitiSelect<T extends boolean = true> {
  vrsta?: T;
  status?: T;
  poslovnica?: T;
  dodijeljeno?: T;
  ime?: T;
  telefon?: T;
  email?: T;
  poruka?: T;
  preferiraniTermin?: T;
  proizvod?: T;
  izvorStranica?: T;
  saglasnost?: T;
  biljeske?:
    | T
    | {
        tekst?: T;
        autor?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poslovnice_select".
 */
export interface PoslovniceSelect<T extends boolean = true> {
  naziv?: T;
  slug?: T;
  grad?: T;
  adresa?: T;
  geoSirina?: T;
  geoDuzina?: T;
  telefoni?:
    | T
    | {
        oznaka?: T;
        broj?: T;
        id?: T;
      };
  emaili?:
    | T
    | {
        email?: T;
        id?: T;
      };
  viber?: T;
  whatsapp?: T;
  radnoVrijeme?:
    | T
    | {
        dan?: T;
        od?: T;
        do?: T;
        zatvoreno?: T;
        id?: T;
      };
  radnoVrijemePotvrdjeno?: T;
  fotografije?: T;
  opis?: T;
  googleMapsLink?: T;
  novaPoslovnica?: T;
  aktivna?: T;
  redoslijed?: T;
  seo?:
    | T
    | {
        naslov?: T;
        opis?: T;
        slika?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proizvodi_select".
 */
export interface ProizvodiSelect<T extends boolean = true> {
  naziv?: T;
  slug?: T;
  nacin?: T;
  kategorija?: T;
  brend?: T;
  tipAparata?: T;
  cijena?: T;
  staraCijena?: T;
  cijenaOd?: T;
  cijenaDo?: T;
  cijenaNapomena?: T;
  kratkiOpis?: T;
  opis?: T;
  slike?: T;
  istaknut?: T;
  aktivan?: T;
  legacyHandle?: T;
  seo?:
    | T
    | {
        naslov?: T;
        opis?: T;
        slika?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usluge_select".
 */
export interface UslugeSelect<T extends boolean = true> {
  naziv?: T;
  slug?: T;
  kratkiOpis?: T;
  ikona?: T;
  koraci?:
    | T
    | {
        naslov?: T;
        opis?: T;
        id?: T;
      };
  trajanje?: T;
  zaKoga?: T;
  sadrzaj?: T;
  slika?: T;
  redoslijed?: T;
  aktivna?: T;
  seo?:
    | T
    | {
        naslov?: T;
        opis?: T;
        slika?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "akcije_select".
 */
export interface AkcijeSelect<T extends boolean = true> {
  naslov?: T;
  slug?: T;
  kratkiOpis?: T;
  sadrzaj?: T;
  slika?: T;
  vrijediOd?: T;
  vrijediDo?: T;
  proizvodi?: T;
  poslovnice?: T;
  istaknutaNaPocetnoj?: T;
  seo?:
    | T
    | {
        naslov?: T;
        opis?: T;
        slika?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "objave_select".
 */
export interface ObjaveSelect<T extends boolean = true> {
  naslov?: T;
  slug?: T;
  kategorija?: T;
  datumObjave?: T;
  izvod?: T;
  naslovnaSlika?: T;
  sadrzaj?: T;
  autor?: T;
  seo?:
    | T
    | {
        naslov?: T;
        opis?: T;
        slika?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cesta-pitanja_select".
 */
export interface CestaPitanjaSelect<T extends boolean = true> {
  _order?: T;
  pitanje?: T;
  odgovor?: T;
  grupa?: T;
  naPocetnoj?: T;
  aktivno?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tim_select".
 */
export interface TimSelect<T extends boolean = true> {
  ime?: T;
  titula?: T;
  fotografija?: T;
  poslovnica?: T;
  jezici?:
    | T
    | {
        jezik?: T;
        id?: T;
      };
  biografija?: T;
  redoslijed?: T;
  aktivan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recenzije_select".
 */
export interface RecenzijeSelect<T extends boolean = true> {
  ime?: T;
  poslovnica?: T;
  tekst?: T;
  ocjena?: T;
  odobreno?: T;
  istaknuta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediji_select".
 */
export interface MedijiSelect<T extends boolean = true> {
  alt?: T;
  lqip?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        mala?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        srednja?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        velika?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xl?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        puna?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "korisnici_select".
 */
export interface KorisniciSelect<T extends boolean = true> {
  ime?: T;
  uloga?: T;
  poslovnica?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Tekstovi i baneri na početnoj stranici.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pocetna".
 */
export interface Pocetna {
  id: number;
  hero: {
    naslov: string;
    podnaslov?: string | null;
    ctaTekst?: string | null;
  };
  sarajevoBaner?: {
    aktivan?: boolean | null;
    tekst?: string | null;
    link?: string | null;
  };
  povjerenje?: {
    godineRada?: number | null;
    /**
     * npr. broj zadovoljnih korisnika — unesite samo provjerene podatke.
     */
    statistike?:
      | {
          broj: string;
          oznaka: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Prevlačenjem mijenjate redoslijed sekcija. Sekcije koje uklonite se ne prikazuju.
   */
  redoslijedSekcija?:
    | {
        sekcija:
          | 'koraci'
          | 'poslovnice'
          | 'tipovi'
          | 'usluge'
          | 'povjerenje'
          | 'recenzije'
          | 'akcija'
          | 'pitanja'
          | 'kontakt';
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Linkovi u zaglavlju (najviše 7) i kolone u podnožju stranice.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigacija".
 */
export interface Navigacija {
  id: number;
  /**
   * Najviše 7 stavki. Svaka stavka mora voditi na stvarnu stranicu.
   */
  glavniMeni?:
    | {
        oznaka: string;
        putanja: string;
        id?: string | null;
      }[]
    | null;
  podnozje?:
    | {
        naslov: string;
        linkovi?:
          | {
              oznaka: string;
              putanja: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Osnovna podešavanja stranice — SEO, kontakti, obavještenja.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podesavanja".
 */
export interface Podesavanja {
  id: number;
  nazivSajta: string;
  telefonGlavni?: string | null;
  emailGlavni?: string | null;
  seoNaslov?: string | null;
  seoOpis?: string | null;
  ogSlika?: (number | null) | Mediji;
  /**
   * Na ovu adresu stižu obavještenja ako nije podešen poseban primalac.
   */
  emailZaUpite?: string | null;
  primaoci?:
    | {
        vrsta: 'zakazivanje' | 'doktor' | 'poslovnica' | 'podrska' | 'kupovina' | 'povratni-poziv';
        email: string;
        id?: string | null;
      }[]
    | null;
  facebook?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  /**
   * npr. „audiobm.ba" — ostavite prazno dok se analitika ne podesi.
   */
  plausibleDomena?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pocetna_select".
 */
export interface PocetnaSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        naslov?: T;
        podnaslov?: T;
        ctaTekst?: T;
      };
  sarajevoBaner?:
    | T
    | {
        aktivan?: T;
        tekst?: T;
        link?: T;
      };
  povjerenje?:
    | T
    | {
        godineRada?: T;
        statistike?:
          | T
          | {
              broj?: T;
              oznaka?: T;
              id?: T;
            };
      };
  redoslijedSekcija?:
    | T
    | {
        sekcija?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigacija_select".
 */
export interface NavigacijaSelect<T extends boolean = true> {
  glavniMeni?:
    | T
    | {
        oznaka?: T;
        putanja?: T;
        id?: T;
      };
  podnozje?:
    | T
    | {
        naslov?: T;
        linkovi?:
          | T
          | {
              oznaka?: T;
              putanja?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podesavanja_select".
 */
export interface PodesavanjaSelect<T extends boolean = true> {
  nazivSajta?: T;
  telefonGlavni?: T;
  emailGlavni?: T;
  seoNaslov?: T;
  seoOpis?: T;
  ogSlika?: T;
  emailZaUpite?: T;
  primaoci?:
    | T
    | {
        vrsta?: T;
        email?: T;
        id?: T;
      };
  facebook?: T;
  instagram?: T;
  youtube?: T;
  plausibleDomena?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'objave';
      value: number | Objave;
    } | null;
    global?: string | null;
    user?: (number | null) | Korisnici;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}